### ISSUE TITLE
Column number information

### ISSUE THREAD

**Issue by azawawi** [goccy/p5-Compiler-Lexer#47]
I noticed that the returned token object contains line number information but no column number information. Is there an undocumented feature to access the column number information?

And thanks :+1:

**Comment by briandfoy** [comment]
There isn't an undocumented feature, but I think it is easy to add. Once my latest pull request is merged I'll implement this.

**Comment by goccy** [comment]
@briandfoy Yes, column number is easy to add.
Also, I'm reviewing your pull request (#51). Please wait a little more.

**Comment by briandfoy** [comment]
You've merged my pull request, so you can close this issue.

**Comment by azawawi** [comment]
Thanks for your excellent work. Closing :+1:
