### ISSUE TITLE
Assertion fail in Compiler_scanner.cpp:763

### ISSUE THREAD

**Issue by xsawyerx** [goccy/p5-Compiler-Lexer#77]
```
perl: src/compiler/lexer/Compiler_scanner.cpp:763: Token* Scanner::scanNumber(LexContext*): Assertion `(c == '.' || is_number(c)) && "It do not seem as Number"' failed.
```

**Comment by Leont** [comment]
Figuring out what input triggers this would be helpful.

**Comment by xsawyerx** [comment]
To be honest, I'm not inclined to work on triggering this error again (which might include resetting and rebasing a branch) unless I know this matters. I opened this ticket as a note on the original problems, but it seems like `Compiler::Lexer` is not being maintained or moved to anyone else. Existing PRs are not getting merged and it's sad. :/

**Comment by xsawyerx** [comment]
I cannot recreate the failure so I'm closing this issue.
