### ISSUE TITLE
Please release to CPAN

### ISSUE THREAD

**Issue by xsawyerx** [goccy/p5-Compiler-Lexer#84]
[Perl::LanguageServer](https://metacpan.org/pod/Perl::LanguageServer) notes the following in the POD:

> NOTE: This module uses Compiler::Lexer. The version on cpan (0.22) is buggy crashes from time to time. Please use the version from github (https://github.com/goccy/p5-Compiler-Lexer) until a new version is published to cpan.

Can you please release a new version to CPAN?

Thank you!

**Comment by goccy** [comment]
I released latest version as 0.23 .
( https://metacpan.org/pod/release/GOCCY/Compiler-Lexer-0.23/lib/Compiler/Lexer.pm )

Thanks !!
